# Generated by Django 3.0.8 on 2020-10-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('enrolled', models.CharField(max_length=5000)),
                ('points', models.CharField(max_length=30)),
                ('results', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('contact1', models.CharField(max_length=15)),
                ('contact2', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=90)),
                ('institute', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('hscPassingYear', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('subject1', models.CharField(max_length=30)),
                ('subject2', models.CharField(max_length=30)),
                ('subject3', models.CharField(max_length=30)),
                ('version1', models.CharField(max_length=30)),
                ('version2', models.CharField(max_length=30)),
                ('reasonToAppointAsTeacher', models.CharField(max_length=300)),
            ],
        ),
    ]
