# Generated by Django 3.0.8 on 2020-10-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='lname',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='facebook',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='reasonToAppointAsTeacher',
            field=models.CharField(max_length=500),
        ),
    ]
