# Generated by Django 3.0.8 on 2020-10-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201023_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredTeachers',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('contact1', models.CharField(max_length=15)),
                ('contact2', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('facebook', models.CharField(max_length=250)),
                ('institute', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('hscPass', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('subject1', models.CharField(max_length=30)),
                ('subject2', models.CharField(max_length=30)),
                ('subject3', models.CharField(max_length=30)),
                ('vers1', models.CharField(max_length=30)),
                ('vers2', models.CharField(max_length=30)),
                ('appointment', models.CharField(max_length=500)),
                ('date_of_apply', models.CharField(max_length=30)),
                ('pay', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('vers', models.CharField(max_length=30)),
                ('date_of_joining', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeachersApplied',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('contact1', models.CharField(max_length=15)),
                ('contact2', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('facebook', models.CharField(max_length=250)),
                ('institute', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('hscPass', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('subject1', models.CharField(max_length=30)),
                ('subject2', models.CharField(max_length=30)),
                ('subject3', models.CharField(max_length=30)),
                ('vers1', models.CharField(max_length=30)),
                ('vers2', models.CharField(max_length=30)),
                ('appointment', models.CharField(max_length=500)),
                ('date_of_apply', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
