# Generated by Django 3.0.8 on 2020-10-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201026_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsWithoutOTP',
            fields=[
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('enrolled', models.CharField(default=0, max_length=5000)),
                ('points', models.CharField(max_length=30)),
                ('results', models.CharField(max_length=5000)),
                ('accounts_type', models.CharField(default='Student', max_length=50)),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
    ]
