# Generated by Django 3.0.8 on 2020-10-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentswithoutotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredteachers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teachersapplied',
            name='name',
        ),
        migrations.AddField(
            model_name='registeredteachers',
            name='fname',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='registeredteachers',
            name='lname',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='teachersapplied',
            name='fname',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='teachersapplied',
            name='lname',
            field=models.CharField(default='', max_length=15),
        ),
    ]
