# Generated by Django 3.0.8 on 2020-10-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_allusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredteachers',
            name='subject',
            field=models.CharField(max_length=300),
        ),
    ]
