# Generated by Django 3.0.8 on 2020-11-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201030_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredteachers',
            name='courses',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
