# Generated by Django 3.0.8 on 2020-11-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_registeredteachers_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredteachers',
            name='courseList',
            field=models.CharField(default='', max_length=99999999),
        ),
        migrations.AlterField(
            model_name='registeredteachers',
            name='courses',
            field=models.CharField(default=0, max_length=3000),
        ),
    ]
