# Generated by Django 3.0.8 on 2020-11-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201110_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredteachers',
            name='courseList',
            field=models.CharField(max_length=99999999),
        ),
    ]
