# Generated by Django 3.0.8 on 2020-11-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201111_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredteachers',
            name='classLink',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
