# Generated by Django 3.0.8 on 2020-11-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_registeredteachers_classlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='successRate',
            field=models.CharField(default='', max_length=10),
        ),
    ]
