# Generated by Django 3.0.8 on 2020-11-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_student_successrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='successRate',
            field=models.CharField(max_length=10),
        ),
    ]
