# Generated by Django 3.0.8 on 2020-11-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201118_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quizAttended',
            field=models.CharField(default='', max_length=300),
        ),
    ]
