# Generated by Django 3.0.8 on 2020-11-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_student_quizattended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='quizAttended',
            field=models.CharField(max_length=300),
        ),
    ]
