# Generated by Django 3.0.8 on 2020-11-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201118_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='results',
            field=models.CharField(default='[]', max_length=5000),
        ),
    ]
