# Generated by Django 3.0.8 on 2020-11-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20201120_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentswithoutotp',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentswithoutotp',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
