# Generated by Django 3.0.8 on 2020-10-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('no', models.CharField(max_length=30)),
                ('subj', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HSCChem1st',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='HSCChem2nd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='HSCChemistry1stQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HSCChemistry2ndQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HSCMath1st',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='HSCMath1stQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HSCMath2nd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='HSCMath2ndQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HSCPhysics1st',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='HSCPhysics1stQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HSCPhysics2nd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='HSCPhysics2ndQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JSCMath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='JSCMathQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JSCScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='JSCScienceQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SSCBiology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='SSCChemistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='SSCChemistryQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SSCHMath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='SSCHMathQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SSCMath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='SSCMathQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SSCPhysics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
        migrations.CreateModel(
            name='SSCPhysicsQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
    ]
