# Generated by Django 3.0.8 on 2020-10-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chapterlist_subjslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterlist',
            name='subjSlug',
        ),
    ]
