# Generated by Django 3.0.8 on 2020-10-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_chapterlist_subjslug'),
    ]

    operations = [
        migrations.CreateModel(
            name='allContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chno', models.CharField(max_length=30)),
                ('chapname', models.CharField(max_length=50)),
                ('subj', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=30)),
                ('videoID', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='static/files')),
            ],
        ),
    ]
