# Generated by Django 3.0.8 on 2020-10-22 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_allcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterlist',
            name='subjSlug',
            field=models.CharField(default=datetime.datetime(2020, 10, 22, 17, 15, 44, 445609), max_length=30),
            preserve_default=False,
        ),
    ]
