# Generated by Django 3.0.8 on 2020-10-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_chapterlist_subjslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcontent',
            name='chapSlug',
            field=models.CharField(default='', max_length=30),
        ),
    ]
