# Generated by Django 3.0.8 on 2020-10-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_allcontent_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcontent',
            name='subjSlug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='allcontent',
            name='chapSlug',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='allcontent',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
