# Generated by Django 3.0.8 on 2020-10-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_allcontent_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=10000)),
                ('video', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('chapter', models.CharField(max_length=30)),
                ('datetime', models.CharField(max_length=30)),
            ],
        ),
    ]
