# Generated by Django 3.0.8 on 2020-10-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='replies',
            field=models.CharField(default='', max_length=9999999999999999),
        ),
    ]
