# Generated by Django 3.0.8 on 2020-10-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_comments_replies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('comment_id', models.CharField(max_length=30)),
                ('video', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('chapter', models.CharField(max_length=30)),
                ('datetime', models.CharField(max_length=30)),
                ('reply', models.CharField(max_length=500)),
            ],
        ),
    ]
