# Generated by Django 3.0.8 on 2020-10-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsubjects',
            name='teacher',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='allsubjects',
            name='totLectures',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='allsubjects',
            name='totStudents',
            field=models.CharField(default='', max_length=30),
        ),
    ]
