# Generated by Django 3.0.8 on 2020-11-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
                ('teacher', models.CharField(default='', max_length=30)),
                ('totStudents', models.CharField(default='', max_length=30)),
                ('totLectures', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
