# Generated by Django 3.0.8 on 2020-11-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20201108_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='link',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
