# Generated by Django 3.0.8 on 2020-11-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_courses_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='link',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
