# Generated by Django 3.0.8 on 2020-11-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_enrollment_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionBank',
        ),
    ]
