# Generated by Django 3.0.8 on 2020-11-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='id',
        ),
        migrations.AddField(
            model_name='questions',
            name='quesID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
