# Generated by Django 3.0.8 on 2020-11-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20201112_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='QuestionBank',
        ),
    ]
