# Generated by Django 3.0.8 on 2020-11-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20201112_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizChapterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('no', models.CharField(max_length=30)),
                ('subj', models.CharField(max_length=30)),
                ('subjSlug', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
            ],
        ),
    ]
