# Generated by Django 3.0.8 on 2020-11-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20201114_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
